import type { Metadata } from 'next';
import '../globals.css';
import { Rubik } from 'next/font/google';

const rubik = Rubik({
  variable: '--font-rubik',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.className} ${rubik.className}`}>
        {children}
      </body>
    </html>
  );
}
